inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

Naming/FileName:
  Exclude:
    - lib/smart_answer_flows/*.rb
    - test/fixtures/smart_answer_flows/*.rb

Style/CommentedKeyword:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*.rake'
    - 'lib/smart_answer_flows/**/*.rb'

Rails/OutputSafety:
  Enabled: false
