inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

Style/CommentedKeyword:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*.rake'
    - 'lib/smart_answer_flows/**/*.rb'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'

Rails/OutputSafety:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
