---
"2012":
  first_child: 20.3
  additional_child: 13.4
"2013":
  first_child: 20.3
  additional_child: 13.4
"2014":
  first_child: 20.3
  additional_child: 13.55
"2015":
  first_child: 20.7
  additional_child: 13.7
"2016":
  first_child: 20.7
  additional_child: 13.7
"2017":
  first_child: 20.7
  additional_child: 13.7
"2018":
  first_child: 20.7
  additional_child: 13.7
"2019":
  first_child: 20.7
  additional_child: 13.7
2020:
  first_child: 21.05
  additional_child: 13.95
